### ISSUE TITLE
'Add feed' notification not visible

### ISSUE THREAD

**Issue by hellojaccc** [phedlund/CloudNews#10]
![image](https://user-images.githubusercontent.com/71537512/139566070-f70d3f2f-b9a6-4686-8786-1c560ad44dd8.png)

Please check attachment

**Comment by hellojaccc** [comment]
Copy a rss feed link - CloudNews will show this

**Comment by phedlund** [comment]
How do I reproduce this? I see
![Untitled](https://user-images.githubusercontent.com/884639/141229348-f7880a4c-a141-4028-b436-ad6f8c0c3938.png)

**Comment by hellojaccc** [comment]
I'm on iOS 15, and iPhone SE 2020.

Reinstalling the app didn't fix the issue. 

Might be iOS 15 specific issue?
