### ISSUE TITLE
Error message does not go away

### ISSUE THREAD

**Issue by tflidd** [phedlund/CloudNews#4]
ios: 14.2.1
iphone 12 Pro Max
NC: 18.0.11
news app 14.2.2
Netcloud Coherence for ios 3.0.15.2

Not sure why I got this timeout, perhaps switch between cellular network and home wifi. However, the message couldn't be closed and didn't go away. The app wasn't reacting at all. The server itself was ok, so I had to force a restart of the app then everything worked again.

![20-12-10 08-34-41 4389](https://user-images.githubusercontent.com/8111200/101753394-dcfc5680-3ad2-11eb-99ab-4edb306c5c5b.png)

**Comment by phedlund** [comment]
Error messages can be dismissed by swiping them off screen. Did that not work?

**Comment by tflidd** [comment]
I tried to 'click' on the X. It didn't close, even after switching to a different app and back that message never disappeared. I'm not sure if I tried swiping...
