### ISSUE TITLE
Really annoying bug on iOS 12.4.9 iPhone 6 Nextcloud 20.0.5

### ISSUE THREAD

**Issue by houdini69** [phedlund/CloudNews#5]
Strange behavior of the app. When I click on a news title very often the text does not correspond to the expected one. Most of the time it's the next (or previous?) news and it repeats itself several times. Very annoying.

**Comment by phedlund** [comment]
As a daily user of the app myself I have never seen this. Could provide some more detailed step to reproduce?

**Comment by houdini69** [comment]
Last version seems to have solved this issue. Will post again if needed.

**Comment by phedlund** [comment]
Closing as not reproducible.
