### ISSUE TITLE
Add Safari reader mode support

### ISSUE THREAD

**Issue by adminelix** [phedlund/CloudNews#6]
### Feature Request

If I open an article from the list of all unread articles and click on "View Full Article", the original article appears in an embedded safari browser (I guess).
It would be awesome if the article is opened directly in Safari reader mode.
A configuration if reader mode or not, dark mode or not is also imaginable.

**Comment by phedlund** [comment]
All of this is already supported. The easiest way is to enable full text support already on the server, the second option is to enable reader mode in the app's feed settings (long press on a feed to access its settings).
CloudNews respects the systems light/dark mode and also supports light, sepia, and dark modes from the settings dialog (gear icon).
