### ISSUE TITLE
Navigation in the article list is missing

### ISSUE THREAD

**Issue by MaPhiWe** [phedlund/CloudNews#7]
First, thank you very much for this great app, that I like a lot and use daily!

On the iPad, the navigation button in the article list has disappeared, making it very hard to move back to the feed list in the folder view. 

If I reduce the size of the app by splitting the screen, the button appears. It is also available on the iPhone.

I hope you can fix this.

Kind regards, MaPhi

**Comment by phedlund** [comment]
I am not able to reproduce the problem. Which model iPad do you have and which version of iOS is it running?

**Comment by MaPhiWe** [comment]
iPad Pro (10,5 Inch)
14.6
CloudNews 3.12.1

![5DD7416E-E663-4D85-B6C1-1AC3A7B3198C](https://user-images.githubusercontent.com/25352021/122664602-b9f9e000-d1a2-11eb-9061-96c09f442e04.png)

**Comment by phedlund** [comment]
Unfortunately I don't own such a device, but when running a simulator with the same configuration I am still unable to reproduce the problem. I know it's a pain but can you try uninstalling and reinstalling the app? Maybe try just rebooting the iPad first.

**Comment by MaPhiWe** [comment]
I already rebooted... didn't help.

Uninstall/Reinstall didn't help either :( 

But if you can't reproduce it, then I'll have to wait if it disappears on its own again eventually.

**Comment by phedlund** [comment]
I found a scenario where I can reproduce (but swiping back from the left screen edge still works). I will work on a fix.

**Comment by MaPhiWe** [comment]
You're a hero!

Yes, swiping from left still works, but has the drawback that it sometimes stars or reads an entry that I didn't want to star/read (yet).

**Comment by MaPhiWe** [comment]
Navigation has been restored with the update. Thank you!
