### ISSUE TITLE
Broken layout when viewing article with images

### ISSUE THREAD

**Issue by hellojaccc** [phedlund/CloudNews#8]
https://user-images.githubusercontent.com/71537512/139541313-431596b2-1517-4aea-badc-f2cf715bbbd0.MOV

Image does not seem to be scaling, this causes problem. 

It's scaling correctly on another viewers.

**Comment by phedlund** [comment]
Hi, can you provide an example feed where this happen? It looks like you are viewing a news site?

**Comment by hellojaccc** [comment]
Example: (http://feedproxy.google.com/~r/slownews/~3/vCp3UBjZbAQ/82344)
