### ISSUE TITLE
3 dot button icon position broken

### ISSUE THREAD

**Issue by hellojaccc** [phedlund/CloudNews#9]
![image](https://user-images.githubusercontent.com/71537512/139541378-5be037ad-c67a-4f7a-8f22-be5dd321477f.jpeg)

Its position is different from others

**Comment by phedlund** [comment]
Hi, I fail to see how it's positioned differently?

**Comment by hellojaccc** [comment]
It's not in center of status bar unlike others

![image](https://user-images.githubusercontent.com/71537512/139566031-4afb7385-e2c2-4241-8229-e440f8408931.jpeg)
